language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
script:
- "./gradlew build"
deploy:
  provider: heroku
  app: blog-de-juan-153247293
  api_key:
    secure: ZiswPD+45QAw6k4LCBVsjhdfL2pfXdaSmtsCXBHPuPRDHq1CrMrDV09o6urOvv/vBUC0Raj96A5Gz+kxEP7iThuiOhcS0iSY/P3RyNyfWqFtz2Vfhj6OcLOTGrvrRljjNOm1U+FDbqjtRRS7HworCQq8M+h5Lt/3V2beGOe/lWdJX6VA3AvqbxChhm+j7QA/dR9Y4n5oHieHueln4qxFu0T0AXol+mXlCLEdmNIb74zeEeba3r8kWzVdWD7LIaCGK8HS4laGhzu4kcWptXKdAHFsgmNrbxqMZPf5eAJnjvFoiwPegHrAL8dGBWcqzGKZQQ+AZ5esafEYsMJRGqTDxvKeQQiiZExwaURNiOX4d7JwXZifyDs1Z1rV4e7k6T/Hy2C9IEzMpJ3ACi+yObPWYLyZtaTkpWVZzlOpg9pqk8G02Ks8ARAsgsFHFPfRVjnpBKWkGTZQ0eM72FOCDRxHI4ed8TqHbYK+Fn1HPwEmP2zSA9sq+jDCuuwZdYNkjFoH0/l/tOnGMwhEOaygK6MET8ekanZw4FwvIb6ZZ5rIwvYAIzd3UzNU4GB+och4IgNMKH5wA6gUPpIyyoqwgges0nDEzTwZ3r+KJ3EHOa0uVRQsKWez4V1tbvb1+a8KbGAYsmMRgR6vjy7Ft9FuQKhJ611aIsFSvO75t41heZdoCbM=
